import { Category } from '../types';

export const CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Phe Gài',
    count: 681,
    subcategories: ['Phe gài trục', 'Phe gài lỗ', 'Phe gài chữ E', 'Phe gài đặc biệt', 'Dụng cụ lắp phe'],
    relatedItems: ['Phe gài trục', 'Phe gài lỗ', 'Hộp phe gài'],
    sections: [
      { title: 'Phổ biến', items: ['Phe gài DIN 471', 'Phe gài DIN 472', 'Phe gài Inox 304'] },
      { title: 'Thương hiệu HOT', items: ['MS-PRO', 'ME-PRO', 'B-FAST'] },
    ],
  },
  {
    id: '2',
    name: 'Ren Cấy',
    count: 431,
    subcategories: ['Ren cấy Inox', 'Ren cấy thép', 'Dụng cụ cấy ren', 'Helicoil', 'Tangless Insert'],
    relatedItems: ['Ren cấy Inox', 'Ren cấy thép', 'Bộ dụng cụ cấy ren'],
    sections: [
      { title: 'Vật liệu', items: ['Thép mạ kẽm', 'Inox 304', 'Inox 316'] },
      { title: 'Ứng dụng', items: ['Sửa chữa ren', 'Gia công nhôm', 'Hàng không'] },
    ],
  },
  {
    id: '3',
    name: 'Bulong',
    count: 3131,
    subcategories: ['Bulong lục giác', 'Bulong lục giác chìm', 'Bulong hệ inch', 'Bulong inox', 'Bulong móng', 'Bulong nhựa'],
    relatedItems: ['Bulong lục giác', 'Bulong lục giác chìm', 'Đai ốc', 'Long đền'],
    sections: [
      { title: 'Tiêu chuẩn', items: ['DIN 933', 'DIN 931', 'DIN 912', 'ISO 4017'] },
      { title: 'Cấp bền', items: ['4.8', '8.8', '10.9', '12.9'] },
    ],
  },
  { id: '4', name: 'Bulong Cổ Vuông', count: 199, subcategories: ['M6', 'M8', 'M10'], relatedItems: ['Bulong cổ vuông M6', 'Bulong cổ vuông M8'] },
  { id: '5', name: 'Bulong Đầu Bông', count: 113, subcategories: ['D5', 'D6', 'D8'], relatedItems: ['Bulong đầu bông D5', 'Bulong đầu bông D6'] },
  { id: '6', name: 'Ốc vít', count: 1205, subcategories: ['Vít gỗ', 'Vít kim loại', 'Vít tự khoan'], relatedItems: ['Vít gỗ đầu lồi', 'Vít đuôi cá', 'Vít bắn tôn'] },
  { id: '7', name: 'Long đền', count: 842, subcategories: ['Long đền phẳng', 'Long đền vênh'], relatedItems: ['Long đền phẳng DIN 125', 'Long đền vênh DIN 127', 'Long đền chén'] },
  { id: '8', name: 'Đai ốc', count: 2100, relatedItems: ['Đai ốc lục giác', 'Đai ốc khóa', 'Đai ốc tai hồng'] },
  { id: '9', name: 'Thanh ren', count: 540, relatedItems: ['Thanh ren 1m', 'Thanh ren 2m', 'Thanh ren inox'] },
  { id: '10', name: 'Lục giác', count: 890, relatedItems: ['Lục giác cây', 'Bộ lục giác', 'Lục giác sao'] },
  { id: '11', name: 'Dụng cụ điện', count: 120 },
  { id: '12', name: 'Bảo hộ lao động', count: 350 },
  { id: '13', name: 'Keo & Băng keo', count: 210 },
  { id: '14', name: 'Phụ kiện ống', count: 430 },
  { id: '15', name: 'Thiết bị đo', count: 95 },
  { id: '16', name: 'Bulong Cánh Chuồn', count: 85, relatedItems: ['Bulong cánh chuồn Inox', 'Bulong cánh chuồn M6', 'Bulong cánh chuồn M8'] },
  { id: '17', name: 'Bulong Mắt', count: 120, relatedItems: ['Bulong mắt DIN 444', 'Bulong mắt M12', 'Bulong mắt M16'] },
  { id: '18', name: 'Bulong Hàn', count: 95, relatedItems: ['Bulong hàn đồng', 'Bulong hàn inox', 'Máy hàn bulong'] },
  { id: '19', name: 'Lục Giác Chìm', count: 1540, relatedItems: ['Lục giác chìm đầu trụ', 'Lục giác chìm đầu cầu', 'Lục giác chìm đầu bằng'] },
  { id: '20', name: 'Tăng Đơ Cáp', count: 320, relatedItems: ['Tăng đơ 2 đầu tròn', 'Tăng đơ 1 đầu móc', 'Tăng đơ inox'] },
  { id: '21', name: 'Ma Ní Chống Xoắn', count: 150, relatedItems: ['Ma ní chữ U', 'Ma ní bầu', 'Ma ní xoay'] },
  { id: '22', name: 'Đai Siết Ống', count: 560, relatedItems: ['Đai siết ống inox', 'Đai siết ống nhựa', 'Đai siết dây'] },
  { id: '23', name: 'Vòng Bi Bạc Đạn', count: 2100, relatedItems: ['Vòng bi cầu', 'Vòng bi đũa', 'Vòng bi tì'] },
  { id: '24', name: 'Mũi Khoan', count: 1200, relatedItems: ['Mũi khoan bê tông', 'Mũi khoan sắt', 'Mũi khoan gỗ'] },
  { id: '25', name: 'Máy Khoan', count: 450, relatedItems: ['Máy khoan pin', 'Máy khoan búa', 'Máy khoan cầm tay'] },
];
